"""Delete email confirmation

Revision ID: fad6af5a3764
Revises: 19a2d57893d8
Create Date: 2025-08-24 10:42:56.456527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad6af5a3764'
down_revision = '19a2d57893d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_password_reset_token'), type_='unique')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subscription_pair'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_column('confirmation_token')
        batch_op.drop_column('is_confirmed')
        batch_op.drop_column('confirmation_sent_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_sent_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_confirmed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_subscription_pair'), ['subscriber_id', 'subscribed_to_id'])

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_password_reset_token'), ['token'])

    # ### end Alembic commands ###
